/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.User;

/**
 *
 * @author samps
 */
public class FormJPanel extends javax.swing.JPanel {
    
    JPanel bottomPanel;
    ImageIcon picture;
    /**
     * Creates new form FormJPanel
     */
    public FormJPanel() {
        initComponents();
    }
    public FormJPanel(JPanel bottomPanel){
    initComponents();
    this.bottomPanel = bottomPanel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        firstnameTextField = new javax.swing.JTextField();
        lastnameLabel = new javax.swing.JLabel();
        lastnameTextField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        ageTextField = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        phonenumberLabel = new javax.swing.JLabel();
        phonenumberTextField = new javax.swing.JTextField();
        emailaddressLabel = new javax.swing.JLabel();
        emailaddressTextField = new javax.swing.JTextField();
        hobbiesLabel = new javax.swing.JLabel();
        hobbisScrollPane = new javax.swing.JScrollPane();
        hobbiesTextArea = new javax.swing.JTextArea();
        imgLabel = new javax.swing.JLabel();
        PictureButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Create User Profile");

        firstnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        firstnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstnameLabel.setText("First Name");

        lastnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lastnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastnameLabel.setText("Last Name");

        genderLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Gender");

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Unspecified" }));
        genderComboBox.setSelectedIndex(-1);

        ageLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel.setText("Age");

        phonenumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        phonenumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        phonenumberLabel.setText("Phone Number");

        emailaddressLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailaddressLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailaddressLabel.setText("Email Address");

        hobbiesLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hobbiesLabel.setForeground(new java.awt.Color(255, 255, 255));
        hobbiesLabel.setText("Hobbies");

        hobbiesTextArea.setColumns(20);
        hobbiesTextArea.setRows(5);
        hobbisScrollPane.setViewportView(hobbiesTextArea);

        imgLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        imgLabel.setForeground(new java.awt.Color(255, 255, 255));
        imgLabel.setText("Profile Photo");

        PictureButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        PictureButton.setText("Upload");
        PictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PictureButtonActionPerformed(evt);
            }
        });

        submitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(genderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phonenumberLabel)
                            .addComponent(emailaddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(hobbiesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(genderComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phonenumberTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                    .addComponent(emailaddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hobbisScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PictureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(submitButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstnameLabel)
                            .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastnameLabel)
                            .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderLabel)
                            .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageLabel)
                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phonenumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phonenumberLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailaddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailaddressLabel))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hobbisScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hobbiesLabel))
                        .addGap(123, 123, 123))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PictureButton))))
                .addComponent(submitButton)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PictureButtonActionPerformed
        // TODO add your handling code here:
        //Photo upload logic
        JFileChooser file = new JFileChooser();
        if (file.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            try {
                BufferedImage img = ImageIO.read(file.getSelectedFile());
                if (img != null) {
                    Image edited_image = img.getScaledInstance(60, 80, Image.SCALE_SMOOTH);
                    this.picture = new ImageIcon(edited_image);
                    imgLabel.setIcon(picture);
                    //imgLabel.setText(file.getSelectedFile().getAbsolutePath());
                    //this.userInfo.setPic(new ImageIcon(edited_image));
                } else {
                    JOptionPane.showMessageDialog(this, "Selected file is not an image.", "Error - Incorrect image", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Please upload image correctly.", "Error - Incorrect image", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_PictureButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        //1. Declaring and Initializing Object Variable
        try{
            User userObject = new User();

            //2. Get data from the text field
            userObject.setFirstname(this.firstnameTextField.getText());
            userObject.setLastname(this.lastnameTextField.getText());
            userObject.setGender(this.genderComboBox.getSelectedItem().toString());
            userObject.setAge(Integer.parseInt(this.ageTextField.getText()));
            userObject.setEmailaddress(this.emailaddressTextField.getText());
            userObject.setPhonenumber(this.phonenumberTextField.getText());
            userObject.setHobbies(this.hobbiesTextArea.getText());
            userObject.setPicture(this.picture);

            //3. Display information to the user (as a pop up)
            System.out.println(userObject.getFirstname());
            System.out.println(userObject.getLastname());
            System.out.println(userObject.getGender());
            System.out.println(userObject.getAge());
            System.out.println(userObject.getEmailaddress());
            System.out.println(userObject.getPhonenumber());
            System.out.println(userObject.getHobbies());
            System.out.println(userObject);

            //4. Creating pop up to screen
            if (userObject.getFirstname().isBlank())
            {JOptionPane.showMessageDialog(this, "First name is required", "Oops", HEIGHT);
            }else if (userObject.getLastname().isBlank())
            {JOptionPane.showMessageDialog(this, "Last name is required", "Oops", HEIGHT);
            }else if (userObject.getPhonenumber().isBlank())
            {JOptionPane.showMessageDialog(this, "Please provide your phone number", "Oops", HEIGHT);
            }else if (userObject.getEmailaddress().isBlank())
            {JOptionPane.showMessageDialog(this, "Please provide your email address", "Oops", HEIGHT);
            }else
            {JOptionPane.showMessageDialog(this, userObject, "Success!", HEIGHT, this.picture);
            
            //Navigate to the View J Panel
            ViewJPanel viewJPanelObject = new ViewJPanel(userObject);
            this.bottomPanel.add(viewJPanelObject);
            CardLayout layout = (CardLayout)
            this.bottomPanel.getLayout();
            layout.next(bottomPanel);
            }

            //5. //NullPointerException when the user does not select any gender
        }catch (NullPointerException npe)
        {JOptionPane.showMessageDialog(this, "Please select your gender", "Cannot Proceed!", HEIGHT);
        }catch (NumberFormatException nfe)
        {JOptionPane.showMessageDialog(this, "Oops! Input a number for age. ", "Failed", HEIGHT);
        } catch (Exception e)
        {JOptionPane.showMessageDialog(this, "Oops! Something went wrong. Please try again ", "Failed", HEIGHT);}

    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PictureButton;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel emailaddressLabel;
    private javax.swing.JTextField emailaddressTextField;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel hobbiesLabel;
    private javax.swing.JTextArea hobbiesTextArea;
    private javax.swing.JScrollPane hobbisScrollPane;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JLabel phonenumberLabel;
    private javax.swing.JTextField phonenumberTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
