package UI;

import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author samps
 */
public class Lab2AssignmentJFrame extends javax.swing.JFrame {

    /**
     * Creates new form Lab2AssignmentJFrame
     */
    public Lab2AssignmentJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderbuttonGroup = new javax.swing.ButtonGroup();
        createuserprofilePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        lastnameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        phonenumberLabel = new javax.swing.JLabel();
        emailaddressLabel = new javax.swing.JLabel();
        femaleRadioButton = new javax.swing.JRadioButton();
        firstnameTextField = new javax.swing.JTextField();
        lastnameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        phonenumberTextField = new javax.swing.JTextField();
        emailaddressTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        PictureButton = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 153));

        createuserprofilePanel.setBackground(new java.awt.Color(0, 153, 51));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Create User Profile");

        firstnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        firstnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstnameLabel.setText("First Name");

        lastnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lastnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastnameLabel.setText("Last Name");

        genderLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Gender");

        ageLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel.setText("Age");

        genderbuttonGroup.add(maleRadioButton);
        maleRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maleRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        maleRadioButton.setText("Male");
        maleRadioButton.setActionCommand("M");

        phonenumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        phonenumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        phonenumberLabel.setText("Phone Number");

        emailaddressLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailaddressLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailaddressLabel.setText("Email Address");

        genderbuttonGroup.add(femaleRadioButton);
        femaleRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        femaleRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        femaleRadioButton.setText("Female");
        femaleRadioButton.setActionCommand("F");
        femaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioButtonActionPerformed(evt);
            }
        });

        submitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        genderbuttonGroup.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Unspecified");
        jRadioButton1.setActionCommand("U");

        PictureButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        PictureButton.setText("Upload");
        PictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PictureButtonActionPerformed(evt);
            }
        });

        imgLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        imgLabel.setForeground(new java.awt.Color(255, 255, 255));
        imgLabel.setText("Profile Photo");

        javax.swing.GroupLayout createuserprofilePanelLayout = new javax.swing.GroupLayout(createuserprofilePanel);
        createuserprofilePanel.setLayout(createuserprofilePanelLayout);
        createuserprofilePanelLayout.setHorizontalGroup(
            createuserprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createuserprofilePanelLayout.createSequentialGroup()
                .addGroup(createuserprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createuserprofilePanelLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(submitButton))
                    .addGroup(createuserprofilePanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(createuserprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(createuserprofilePanelLayout.createSequentialGroup()
                                .addGroup(createuserprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(createuserprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lastnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                        .addComponent(genderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(phonenumberLabel)
                                    .addComponent(emailaddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(121, 121, 121)
                                .addGroup(createuserprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(createuserprofilePanelLayout.createSequentialGroup()
                                        .addComponent(maleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(femaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(createuserprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phonenumberTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(createuserprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(PictureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailaddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        createuserprofilePanelLayout.setVerticalGroup(
            createuserprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createuserprofilePanelLayout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(createuserprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameLabel)
                    .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createuserprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastnameLabel)
                    .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createuserprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(maleRadioButton)
                    .addComponent(femaleRadioButton)
                    .addComponent(jRadioButton1))
                .addGap(18, 18, 18)
                .addGroup(createuserprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createuserprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonenumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenumberLabel))
                .addGap(18, 18, 18)
                .addGroup(createuserprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailaddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailaddressLabel))
                .addGap(93, 93, 93)
                .addGroup(createuserprofilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PictureButton))
                .addGap(91, 91, 91)
                .addComponent(submitButton)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(createuserprofilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createuserprofilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void femaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        //1. Declaring Variables
        try{
        String firstname;
        String lastname;
        String gender;
        int age;
        String emailaddress;
        String phonenumber;
        
        //2. Initializing Variables
        firstname = this.firstnameTextField.getText();
        lastname = this.lastnameTextField.getText();
        gender = this.genderbuttonGroup.getSelection().getActionCommand();
        age = Integer.parseInt(this.ageTextField.getText());
        emailaddress = this.emailaddressTextField.getText();
        phonenumber = this.phonenumberTextField.getText();
        
        //3. Display information to the user (as a pop up)
        System.out.println(firstname);
        System.out.println(lastname);
        System.out.println(gender);
        System.out.println(age);
        System.out.println(emailaddress);
        System.out.println(phonenumber);
        
        //4. Creating pop up to screen
        if (firstname.isBlank())
            {JOptionPane.showMessageDialog(rootPane, "First name is required", "Oops", HEIGHT);
            }else if (lastname.isBlank())
            {JOptionPane.showMessageDialog(rootPane, "Last name is required", "Oops", HEIGHT);
            }else if (phonenumber.isBlank())
            {JOptionPane.showMessageDialog(rootPane, "Please provide your phone number", "Oops", HEIGHT);
            }else if (emailaddress.isBlank())
            {JOptionPane.showMessageDialog(rootPane, "Please provide your email address", "Oops", HEIGHT);
            }else         
            {JOptionPane.showMessageDialog(rootPane, "Profile successfully created, " + firstname, "Success!", HEIGHT);
        }
        
       //5. //NullPointerException when the user does not select any gender
        }catch (NullPointerException npe)
        {JOptionPane.showMessageDialog(rootPane, "Please select your gender", "Cannot Proceed!", HEIGHT);
        }catch (Exception e1)
        {JOptionPane.showMessageDialog(rootPane, "Oops! Something went wrong; Input a number for age. ", "Failed", HEIGHT);}
               
    }//GEN-LAST:event_submitButtonActionPerformed

    private void PictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PictureButtonActionPerformed
        // TODO add your handling code here:
        

JFileChooser file = new JFileChooser();
if (file.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
    try {
        BufferedImage img = ImageIO.read(file.getSelectedFile());
        if (img != null) {
            Image edited_image = img.getScaledInstance(60, 80, Image.SCALE_SMOOTH);
            imgLabel.setIcon(new ImageIcon(edited_image));
            imgLabel.setText(file.getSelectedFile().getAbsolutePath());
           // this.userInfo.setPic(new ImageIcon(edited_image)); 
        } else {
            JOptionPane.showMessageDialog(this, "Selected file is not an image.", "Error - Incorrect image", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Please upload image correctly.", "Error - Incorrect image", JOptionPane.ERROR_MESSAGE);
    }
}


    }//GEN-LAST:event_PictureButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab2AssignmentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab2AssignmentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab2AssignmentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab2AssignmentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab2AssignmentJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PictureButton;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JPanel createuserprofilePanel;
    private javax.swing.JLabel emailaddressLabel;
    private javax.swing.JTextField emailaddressTextField;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JLabel genderLabel;
    private javax.swing.ButtonGroup genderbuttonGroup;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JLabel phonenumberLabel;
    private javax.swing.JTextField phonenumberTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
